### ISSUE TITLE
Global transliteration preferences

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#13]
* Python Interface to Cologne Digital Sanskrit Lexicon (CDSL) version: 0.2.1
* Python version: 3.9.1
* Operating System: Bodhi Linux 6

### Description

Allow global setting of input transliteration and output transliteration over and above dictionary / entry level control.
`CDSL.input_transliteration('itrans')`
`CDSL.output_transliteration('devanagari')`
This should take all queries in itrans and give all output in devanagari.
Users have their transliteration predilictions cutting across dictionaries. They usually use the same schemes across dictionaries.

### What I Did

```
Feature request.
```

**Comment by drdhaval2785** [comment]
Also something like this
`results = CDSL.search(query="राम", dictionary="MW", intran='slp1', outtran='iast')`
`results = CDSL.entry(entrynum='123532', , dictionary="MW", intran='slp1', outtran='iast')`

**Comment by drdhaval2785** [comment]
You can specify the overruling as below
Global corpus level
Dictionary level
Search level
Entry level

first has the lowest precedence and last has highest precedence.

If I have set slp1 as input transliteration and specify at search level that I want iast as input transliteration, my search level transliteration should take precedence.

**Comment by hrishikeshrt** [comment]
When would a developer need this? 
In general, as far as I can think, a developer would not have many schemes in mind, and would rarely want input and output in different schemes. 

* Currently, `CDSLCorpus` class does have a feature of specifying scheme at the time of initialization, e.g. `CDSLCorpus(scheme='iast')` which will then do input-output in IAST for underlying dicts.
* Same is also specifiable for `CDSLDict`.
* I am working on providing transliteration options for the `search` function in the `CDSLDict`.
* If the user does require output in a different scheme, every entry has a feature to transliterate into any scheme.

So, I believe Corpus level, Dictionary level and Entry level transliteration is already present and I plan to add preferences for search level.

In general, I am all for simplifying the REPL interface and CLI. I am a bit apprehensive about oversimplification from development point of view, as I think the use-cases won't require it.
Please let me know your thoughts.

**Comment by drdhaval2785** [comment]
Why tie down input scheme and output scheme as the same in CDSLCorpus and elsewhere. There are cases where I would need input in SLP1 (from machine readable data) and output in Devanagari (for human consumption).

Kind request to allow setting up input and output transliteration separately as far as possible.

**Comment by hrishikeshrt** [comment]
Version `0.3.0` adds support for this. Class initialization takes `input_scheme` and `output_scheme` argument.
Same is true for `.search()` function.
`.entry()` and `.dump()` functions take `output_scheme` argument.
