### ISSUE TITLE
CLI minor edit

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#19]
* PyCDSL version:
* Python version:
* Operating System:

### Description

usage: CLI for PyCDSL [-h] [-i] [-s SEARCH] [-p PATH] [-d DICTS [DICTS ...]] [-is INPUT_SCHEME] [-os OUTPUT_SCHEME] [-u] [-dbg]

needs to be changed to

usage: cdsl [-h] [-i] [-s SEARCH] [-p PATH] [-d DICTS [DICTS ...]] [-is INPUT_SCHEME] [-os OUTPUT_SCHEME] [-u] [-dbg]

**Comment by hrishikeshrt** [comment]
Fixed in 6565c4749452ad5f633506100798c5a974ff3ca7
