### ISSUE TITLE
Credit to CDSL

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#21]
* PyCDSL version:
* Python version:
* Operating System:

### Description

Add credits to CDSL as per credits policy of Cologne website. 

### Documentation

Fair use requirement.

**Comment by drdhaval2785** [comment]
Template:

This website / application uses data from [Cologne Digital Sanskrit Dictionaries](https://www.sanskrit-lexicon.uni-koeln.de/), Cologne University, accessed on February 13, 2022.

**Comment by hrishikeshrt** [comment]
Will do it soon. 
It'll appear on PyPI in the next patch release, which is due either tonight or tomorrow.

**Comment by hrishikeshrt** [comment]
The project description currently does link to the Cologne website, but yes I'll add explicit credits.

**Comment by hrishikeshrt** [comment]
@drdhaval2785 Is the `access of February 13, 2022` part required? If so, the `Credits` would need to be updated very frequently.

Is this a valid option?

```
This application uses data from [Cologne Digital Sanskrit Dictionaries](https://www.sanskrit-lexicon.uni-koeln.de/), Cologne University.
```

**Comment by drdhaval2785** [comment]
It is a valid option.
