### ISSUE TITLE
[QUESTION] Is there a way to search for or detect root words?

### ISSUE THREAD

**Issue by ma08** [hrishikeshrt/PyCDSL#28]
Great library btw!! Thanks for your contribution!

Is there a way to filter for only the entries of root Sanskrit words when searching an English-Sanskrit dictionary?

**Comment by drdhaval2785** [comment]
By roots do you mean Sanskrit verbs?

**Comment by drdhaval2785** [comment]
By roots do you mean Sanskrit verbs?

**Comment by hrishikeshrt** [comment]
In case you mean verbs, you may utilize regex patterns (which search supports)

If you are using interactive shell, you can use `show <entry-id> --show-data` to reveal the pattern of data
`*` is used for wildcards

You may observe that verbs have `<i>v.` mentioned in their value.

Now, you can do `set search_mode value` and try to use search command with regex, e.g. `search "take*<i>v."`

Let me know if this solves your needs

**Comment by ma08** [comment]
Thanks @hrishikeshrt and @drdhaval2785 for your quick response.

I don't mean verbs. 

An example of what I mean is the way "root" is used in the explanation of the [H1-H4 tags](https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw010018.pdf) in the MW dictionary. Upon finding this, it became clear to me that I could probably just filter for H1 tags to get what I am looking for.
