### ISSUE TITLE
Error while running REPL

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#5]
* Python Interface to Cologne Digital Sanskrit Lexicon (CDSL) version: 0.1.9
* Python version: 3.6.9
* Operating System: Bodhi LInux 6

### Description

I tried to use MW and search for rAma (slp1).
It gave me errors.

### What I Did

```
(CDSL::None) use MW
(CDSL::MW) scheme slp1
Input scheme: slp1
(CDSL::MW) rAma
Traceback (most recent call last):
  File "/usr/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CDSLShell' object has no attribute 'do_rAma'
```

**Comment by hrishikeshrt** [comment]
I am not sure about the source of this error. Can you please try with a python >= 3.7 environment and see if that fixes it. Something with `cmd` module might have changed that is affecting the default REPL behaviour.

**Comment by hrishikeshrt** [comment]
This issue will be handled with #10. 
Closing it here.
