### ISSUE TITLE
Request for a CLI tool based on Click

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#6]
* Python Interface to Cologne Digital Sanskrit Lexicon (CDSL) version: 0.1.9
* Python version: 3.6.9
* Operating System: Bodhi Linu 6

### Description

I love the REPL session which you have created with the python package.
I would also love to have a simple CLI tool based on Click python package too.

Something like `cdsl [--dict] MW [--input_transliteration=slp1] [--output_transliteration=slp1] rAma` would print the MW entries related to rAma on the terminal itself. 

 
### What I Did

```
Feature request.
```

**Comment by hrishikeshrt** [comment]
This is a great suggestion! I will definitely work on this. 

Is there any specific reason for suggesting `Click` though?
I find python's `argparse` good enough. Additionally, `fire` is a great tool for CLI too.

**Comment by drdhaval2785** [comment]
Nothing in particular for Click. I once wrote a python code, and it was a matter of only a few decorators in click. In no time, the same code which was working for python package, was working as a CLI tool seamlessly. 

You may choose the one which suits you.

**Comment by hrishikeshrt** [comment]
I am moving the REPL to `cdsl -i` or `cdsl --interactive` and otherwise it'll be a normal CLI.  (Reference:  e8b732466e6117f3ccf4a9f14c9a9f1e100aaf35)

This can be tried by cloning the repository and `make install`. 
Currently, CLI is still a work in progress. It'll be complete with the next minor version upgrade.

**Comment by hrishikeshrt** [comment]
Release `0.3.0` adds support for it. 
Documentation is still pending. Will add that soon.
