### ISSUE TITLE
Request for option for output transliteration

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#7]
* Python Interface to Cologne Digital Sanskrit Lexicon (CDSL) version: 0.1.9
* Python version: 3.6.9
* Operating System: Bodhi Linux 6

### Description

Current docs tell that I can tweak the input transliteration.
There are people who would also want to see the output in a specific transliteration of their choice.
They may want to see Devanagari content in IAST / SLP or ITRANS or any other transliteration of their choice.
Kind request to allow this option in python package, REPL session and proposed Click CLI version - all three places.
https://pypi.org/project/indic-transliteration/ may be of help going to and fro various transliteration schemes.

### What I Did

```
Feature request.
```

**Comment by hrishikeshrt** [comment]
`indic-transliteration` is a great library, and is already a dependency. It is used for input scheme selection.
I will look into the output translation as it will require a slight design change.

**Comment by hrishikeshrt** [comment]
Commit 6433eb708fa7ed694ff6a58ef94ff3c415daefd8 adds this functionality. 
Due to the significant under-the-hood changes, I've bumped the minor version and have released `0.2.0`  version.
The documentation has been updated accordingly.

**Comment by drdhaval2785** [comment]
Thanks. It is quite quick.
